package com.akivaliaho;

/**
 * Created by vagrant on 6/24/17.
 */
public enum ExchangeOperation {
    POLL_RESULT_TO_CONFIG_MODULE, POLL_RESULT_TO_CONFIG_MODULE_PARSE_ROUTING_KEY, POLL_RESULT_TO_CONFIG_MODULE_KNOWN_ROUTING_KEY, REQUEST_INTERESTED_PARTIES_FROM_CONFIG, INTERESTED_PARTIES
}
